# ==============================================================
# CONFIGURAÇÕES DO SERVIDOR
# ==============================================================
# A porta que a API vai rodar (Mudei pra 8080 pra não dar conflito com o React que usa a 3000)
server.port=8080

# ==============================================================
# CONFIGURAÇÕES DO POSTGRESQL
# ==============================================================
# Troque "suasenha" pela senha do seu PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/Teste_hotmart
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================================================
# CONFIGURAÇÕES DO HIBERNATE (Mágica do Banco de Dados)
# ==============================================================
# update: Cria as tabelas se não existirem, e atualiza se você mudar o Model
spring.jpa.hibernate.ddl-auto=update

# Mostra no terminal o SQL que o Spring está gerando por trás dos panos
spring.jpa.show-sql=true