spring.datasource.url=jdbc:postgresql://localhost:5432/Teste_hotmart
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate (Isso faz o Spring criar as tabelas sozinho se elas não existirem)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true